name: Pester Tests

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        shell: [pwsh]
        include:
            - os: windows-latest
              shell: powershell
        exclude:
            - os: ubuntu-latest
              shell: powershell
            - os: macos-latest
              shell: powershell
    defaults:
        run:
            shell: ${{ matrix.shell }}
    name: Pester Tests - ${{ matrix.os }} - ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v6

      - name: Install PSGraph
        run: Install-Module -Name PSGraph -Force -Scope CurrentUser

      - name: Install Graphviz
        uses: tlylt/install-graphviz@v1
        if: runner.os != 'Windows'

      - name: Run Pester tests
        uses: PSModule/Invoke-Pester@v4
        id: action-test
        with:
          Path: "./Tests"
          TestResult_Enabled: "true"
          TestResult_OutputPath: "./test-results.xml"
          CodeCoverage_Enabled: "true"
          CodeCoverage_Path: "./Src"
          CodeCoverage_OutputPath: "./coverage.xml"
          CodeCoverage_OutputFormat: "JaCoCo"
          Prescript: |
            Import-Module PSGraph

      - name: Process test results
        if: always()
        run: |
          Write-Output "Total tests: ${{ steps.action-test.outputs.TotalCount }}"
          Write-Output "Passed tests: ${{ steps.action-test.outputs.PassedCount }}"
          Write-Output "Failed tests: ${{ steps.action-test.outputs.FailedCount }}"
          Write-Output "Failed blocks: ${{ steps.action-test.outputs.FailedBlocksCount }}"
          Write-Output "Failed containers: ${{ steps.action-test.outputs.FailedContainersCount }}"
          Write-Output "Test outcome: ${{ steps.action-test.outputs.Result }}"
        shell: ${{ matrix.shell }}

      - name: Take action based on test outcome
        if: steps.action-test.outputs.Result == 'Passed'
        run: echo "All tests passed! Ready to proceed with deployment."